name: BizInfo Crawling Automation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시 (한국 시간)
  workflow_dispatch:  # 수동 실행 추가

jobs:
  bizinfo-crawling:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then
          sudo ln -s $(which chromedriver) /usr/bin/chromedriver
        else
          echo "ChromeDriver 심볼릭 링크가 이미 존재합니다."
        fi
        ls -l /usr/bin/chromedriver  # 링크 확인

    - name: Run crawling script
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "ChromeDriver 버전 확인:"
        /usr/bin/chromedriver --version
        python 1_searching.py
