name: BizInfo Crawling Automation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시 (한국 시간)
  workflow_dispatch:  # 수동 실행 추가

jobs:
  bizinfo-crawling:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        if [ -f "/usr/bin/chromedriver" ]; then
          sudo rm /usr/bin/chromedriver  # 기존 심볼릭 링크가 있으면 삭제
        fi
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver  # 새로 심볼릭 링크 생성

    - name: Run crawling script
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "ChromeDriver 버전 확인:"
        chromedriver --version
        python 1_searching.py
