name: BizInfo Crawling Automation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시 (한국 시간)

  workflow_dispatch:  # 수동 실행 지원

jobs:
  bizinfo-crawling:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

- name: Download ChromeDriver
  run: wget --auth-no-challenge --header='Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
    https://github.com/ghksdl8583r/bizinfo_crawling/releases/download/v1.0.0/chromedriver.exe -O ./chromedriver.exe

    - name: Execute crawling script
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python 1_searching.py
