name: BizInfo Crawling Automation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시 (한국 시간)
  workflow_dispatch:  # 수동 실행 추가

jobs:
  bizinfo-crawling:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        which chromedriver || echo "ChromeDriver 설치 위치를 찾지 못했습니다."
        sudo ln -sf $(which chromedriver) /usr/bin/chromedriver  # 정확한 위치로 심볼릭 링크 생성

    - name: Run crawling script
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "ChromeDriver 버전 확인:"
        /usr/bin/chromedriver --version  # 심볼릭 링크 위치로 확인
        python 1_searching.py
